name: Example - Triage Failed Workflows

on:
  # Trigger when another workflow completes
  workflow_run:
    workflows: ["Your Test Workflow Name"]
    types:
      - completed

jobs:
  triage:
    runs-on: ubuntu-latest
    # Only run if the workflow failed
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    
    steps:
      - name: Analyze Failed Workflow
        uses: adept-at/adept-triage-agent@v1.0.2
        id: triage
        with:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ github.token }}
          # Use the workflow run ID from the completed workflow
          WORKFLOW_RUN_ID: ${{ github.event.workflow_run.id }}
      
      - name: Create Issue for Product Bugs
        if: ${{ steps.triage.outputs.verdict == 'PRODUCT_ISSUE' }}
        uses: actions/github-script@v6
        with:
          script: |
            const workflowRun = context.payload.workflow_run;
            const verdict = '${{ steps.triage.outputs.verdict }}';
            const confidence = '${{ steps.triage.outputs.confidence }}';
            const summary = '${{ steps.triage.outputs.summary }}';
            const reasoning = '${{ steps.triage.outputs.reasoning }}';
            
            const issueBody = [
              '## AI Analysis detected a product issue',
              '',
              `**Workflow:** [${workflowRun.name}](${workflowRun.html_url})`,
              `**Verdict:** ${verdict} (${confidence}% confidence)`,
              `**Summary:** ${summary}`,
              '',
              '### Reasoning',
              reasoning,
              '',
              '### Details',
              `- Workflow Run: #${workflowRun.run_number}`,
              `- Commit: ${workflowRun.head_sha.substring(0, 7)}`,
              `- Branch: ${workflowRun.head_branch}`,
              '',
              'This issue was automatically created by the AI triage agent.'
            ].join('\n');
            
            await github.rest.issues.create({
              ...context.repo,
              title: `🐛 Product Issue: ${workflowRun.name} failed`,
              body: issueBody,
              labels: ['bug', 'ai-detected', 'needs-triage']
            });
      
      - name: Notify Slack
        if: always()
        uses: slackapi/slack-github-action@v1.24.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            {
              "text": "Workflow Analysis Complete",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Workflow:* ${{ github.event.workflow_run.name }}\n*Verdict:* ${{ steps.triage.outputs.verdict }}\n*Confidence:* ${{ steps.triage.outputs.confidence }}%\n*Summary:* ${{ steps.triage.outputs.summary }}"
                  }
                }
              ]
            } 