name: Check dist/

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'src/**'
      - 'package.json'
      - 'package-lock.json'
      - 'tsconfig.json'
  pull_request:
    paths:
      - 'src/**'
      - 'package.json'
      - 'package-lock.json'
      - 'tsconfig.json'

jobs:
  check-dist:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Rebuild dist/
      run: |
        npm run build
        npm run package
    
    - name: Compare dist/ directories
      id: diff
      run: |
        if [ "$(git diff --ignore-space-at-eol dist/ | wc -l)" -gt "0" ]; then
          echo "❌ Detected uncommitted changes in dist/ after build."
          echo "Please run 'npm run all' and commit the changes."
          echo ""
          echo "Changed files:"
          git diff --name-only dist/
          echo ""
          echo "Diff:"
          git diff dist/ | head -100
          exit 1
        else
          echo "✅ dist/ is up to date"
        fi
    
    - name: Upload dist diff
      if: failure() && steps.diff.outcome == 'failure'
      uses: actions/upload-artifact@v4
      with:
        name: dist-diff
        path: |
          dist/
