name: Update Major Version Tags

on:
  release:
    types: [published]

jobs:
  update-tags:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get version from tag
        id: get_version
        run: |
          # Extract version from tag (e.g., v1.3.1 -> 1)
          VERSION=${GITHUB_REF#refs/tags/v}
          MAJOR_VERSION=$(echo $VERSION | cut -d. -f1)
          echo "major_version=v$MAJOR_VERSION" >> $GITHUB_OUTPUT
          echo "full_version=$GITHUB_REF_NAME" >> $GITHUB_OUTPUT

      - name: Update major version tag
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          # Force update the major version tag
          git tag -fa ${{ steps.get_version.outputs.major_version }} \
            -m "Update ${{ steps.get_version.outputs.major_version }} to ${{ steps.get_version.outputs.full_version }}"

          git push origin ${{ steps.get_version.outputs.major_version }} --force
